// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: satellite/envoy/accesslog/v3/als.proto

package org.apache.skywalking.satellite.envoy.accesslog.v3;

/**
 * <pre>
 * The new Envoy ALS protocol, work for satellite transmit the ALS message to oap.
 * </pre>
 *
 * Protobuf service {@code satellite.envoy.accesslog.v3.SatelliteAccessLogService}
 */
public  abstract class SatelliteAccessLogService
    implements com.google.protobuf.Service {
  protected SatelliteAccessLogService() {}

  public interface Interface {
    /**
     * <pre>
     * Use the same parameters to transmit access log messages.
     * The only difference is that the identity information (StreamAccessLogsMessage#identity) may occur on each message.
     * Rely on the streaming messages are orderly, so there will be no problems with message processing.
     * Therefore, when the satellite transmits the ALS message, it does not need to open, send and close the stream for each different identity (envoy).
     * As a result, unnecessary streaming operation requests could be reduced, and the satellite becomes more stable when the satellite sends requests to the upstream.
     * Especially when the number of envoys increases, the optimization becomes more obvious.
     * </pre>
     *
     * <code>rpc StreamAccessLogs(stream .envoy.service.accesslog.v3.StreamAccessLogsMessage) returns (.envoy.service.accesslog.v3.StreamAccessLogsResponse);</code>
     */
    public abstract void streamAccessLogs(
        com.google.protobuf.RpcController controller,
        io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsMessage request,
        com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new SatelliteAccessLogService() {
      @java.lang.Override
      public  void streamAccessLogs(
          com.google.protobuf.RpcController controller,
          io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsMessage request,
          com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse> done) {
        impl.streamAccessLogs(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.streamAccessLogs(controller, (io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsMessage)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsMessage.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   * Use the same parameters to transmit access log messages.
   * The only difference is that the identity information (StreamAccessLogsMessage#identity) may occur on each message.
   * Rely on the streaming messages are orderly, so there will be no problems with message processing.
   * Therefore, when the satellite transmits the ALS message, it does not need to open, send and close the stream for each different identity (envoy).
   * As a result, unnecessary streaming operation requests could be reduced, and the satellite becomes more stable when the satellite sends requests to the upstream.
   * Especially when the number of envoys increases, the optimization becomes more obvious.
   * </pre>
   *
   * <code>rpc StreamAccessLogs(stream .envoy.service.accesslog.v3.StreamAccessLogsMessage) returns (.envoy.service.accesslog.v3.StreamAccessLogsResponse);</code>
   */
  public abstract void streamAccessLogs(
      com.google.protobuf.RpcController controller,
      io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsMessage request,
      com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return org.apache.skywalking.satellite.envoy.accesslog.v3.SatelliteAlsProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.streamAccessLogs(controller, (io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsMessage)request,
          com.google.protobuf.RpcUtil.<io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsMessage.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends org.apache.skywalking.satellite.envoy.accesslog.v3.SatelliteAccessLogService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void streamAccessLogs(
        com.google.protobuf.RpcController controller,
        io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsMessage request,
        com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse.class,
          io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse streamAccessLogs(
        com.google.protobuf.RpcController controller,
        io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsMessage request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse streamAccessLogs(
        com.google.protobuf.RpcController controller,
        io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsMessage request)
        throws com.google.protobuf.ServiceException {
      return (io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        io.envoyproxy.envoy.service.accesslog.v3.StreamAccessLogsResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:satellite.envoy.accesslog.v3.SatelliteAccessLogService)
}

