// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: satellite/envoy/accesslog/v3/als.proto

package org.apache.skywalking.satellite.envoy.accesslog.v3;

public final class SatelliteAlsProto {
  private SatelliteAlsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&satellite/envoy/accesslog/v3/als.proto" +
      "\022\034satellite.envoy.accesslog.v3\032$envoy/se" +
      "rvice/accesslog/v3/als.proto2\237\001\n\031Satelli" +
      "teAccessLogService\022\201\001\n\020StreamAccessLogs\022" +
      "3.envoy.service.accesslog.v3.StreamAcces" +
      "sLogsMessage\0324.envoy.service.accesslog.v" +
      "3.StreamAccessLogsResponse\"\000(\001BL\n2org.ap" +
      "ache.skywalking.satellite.envoy.accesslo" +
      "g.v3B\021SatelliteAlsProtoP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.envoyproxy.envoy.service.accesslog.v3.AlsProto.getDescriptor(),
        });
    io.envoyproxy.envoy.service.accesslog.v3.AlsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
