// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configuration-service.proto

package org.apache.skywalking.oap.server.configuration.service;

public interface GroupConfigItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupConfigItems)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name is composed by "module name"."provider name"."groupName".
   * </pre>
   *
   * <code>string groupName = 1;</code>
   * @return The groupName.
   */
  java.lang.String getGroupName();
  /**
   * <pre>
   * The name is composed by "module name"."provider name"."groupName".
   * </pre>
   *
   * <code>string groupName = 1;</code>
   * @return The bytes for groupName.
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();

  /**
   * <code>repeated .Config items = 2;</code>
   */
  java.util.List<org.apache.skywalking.oap.server.configuration.service.Config> 
      getItemsList();
  /**
   * <code>repeated .Config items = 2;</code>
   */
  org.apache.skywalking.oap.server.configuration.service.Config getItems(int index);
  /**
   * <code>repeated .Config items = 2;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .Config items = 2;</code>
   */
  java.util.List<? extends org.apache.skywalking.oap.server.configuration.service.ConfigOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .Config items = 2;</code>
   */
  org.apache.skywalking.oap.server.configuration.service.ConfigOrBuilder getItemsOrBuilder(
      int index);
}
