// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configuration-service.proto

package org.apache.skywalking.oap.server.configuration.service;

/**
 * Protobuf type {@code GroupConfigurationResponse}
 */
public final class GroupConfigurationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GroupConfigurationResponse)
    GroupConfigurationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GroupConfigurationResponse.newBuilder() to construct.
  private GroupConfigurationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GroupConfigurationResponse() {
    groupConfigTable_ = java.util.Collections.emptyList();
    uuid_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GroupConfigurationResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GroupConfigurationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              groupConfigTable_ = new java.util.ArrayList<org.apache.skywalking.oap.server.configuration.service.GroupConfigItems>();
              mutable_bitField0_ |= 0x00000001;
            }
            groupConfigTable_.add(
                input.readMessage(org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            uuid_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        groupConfigTable_ = java.util.Collections.unmodifiableList(groupConfigTable_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.skywalking.oap.server.configuration.service.ConfigurationServiceOuterClass.internal_static_GroupConfigurationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.skywalking.oap.server.configuration.service.ConfigurationServiceOuterClass.internal_static_GroupConfigurationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse.class, org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse.Builder.class);
  }

  public static final int GROUPCONFIGTABLE_FIELD_NUMBER = 1;
  private java.util.List<org.apache.skywalking.oap.server.configuration.service.GroupConfigItems> groupConfigTable_;
  /**
   * <pre>
   * Include all groupConfig items.
   * All groupConfigTable.groupName should be not empty,
   * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
   * </pre>
   *
   * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.apache.skywalking.oap.server.configuration.service.GroupConfigItems> getGroupConfigTableList() {
    return groupConfigTable_;
  }
  /**
   * <pre>
   * Include all groupConfig items.
   * All groupConfigTable.groupName should be not empty,
   * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
   * </pre>
   *
   * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.apache.skywalking.oap.server.configuration.service.GroupConfigItemsOrBuilder> 
      getGroupConfigTableOrBuilderList() {
    return groupConfigTable_;
  }
  /**
   * <pre>
   * Include all groupConfig items.
   * All groupConfigTable.groupName should be not empty,
   * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
   * </pre>
   *
   * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
   */
  @java.lang.Override
  public int getGroupConfigTableCount() {
    return groupConfigTable_.size();
  }
  /**
   * <pre>
   * Include all groupConfig items.
   * All groupConfigTable.groupName should be not empty,
   * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
   * </pre>
   *
   * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
   */
  @java.lang.Override
  public org.apache.skywalking.oap.server.configuration.service.GroupConfigItems getGroupConfigTable(int index) {
    return groupConfigTable_.get(index);
  }
  /**
   * <pre>
   * Include all groupConfig items.
   * All groupConfigTable.groupName should be not empty,
   * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
   * </pre>
   *
   * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
   */
  @java.lang.Override
  public org.apache.skywalking.oap.server.configuration.service.GroupConfigItemsOrBuilder getGroupConfigTableOrBuilder(
      int index) {
    return groupConfigTable_.get(index);
  }

  public static final int UUID_FIELD_NUMBER = 2;
  private volatile java.lang.Object uuid_;
  /**
   * <pre>
   * UUID is literal string represents the content of the config table.
   * If groupConfigTable is unchanged, then could response the same uuid, and groupConfigTable is not required.
   * </pre>
   *
   * <code>string uuid = 2;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * UUID is literal string represents the content of the config table.
   * If groupConfigTable is unchanged, then could response the same uuid, and groupConfigTable is not required.
   * </pre>
   *
   * <code>string uuid = 2;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < groupConfigTable_.size(); i++) {
      output.writeMessage(1, groupConfigTable_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uuid_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < groupConfigTable_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, groupConfigTable_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uuid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse)) {
      return super.equals(obj);
    }
    org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse other = (org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse) obj;

    if (!getGroupConfigTableList()
        .equals(other.getGroupConfigTableList())) return false;
    if (!getUuid()
        .equals(other.getUuid())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGroupConfigTableCount() > 0) {
      hash = (37 * hash) + GROUPCONFIGTABLE_FIELD_NUMBER;
      hash = (53 * hash) + getGroupConfigTableList().hashCode();
    }
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GroupConfigurationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GroupConfigurationResponse)
      org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.skywalking.oap.server.configuration.service.ConfigurationServiceOuterClass.internal_static_GroupConfigurationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.skywalking.oap.server.configuration.service.ConfigurationServiceOuterClass.internal_static_GroupConfigurationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse.class, org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse.Builder.class);
    }

    // Construct using org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGroupConfigTableFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (groupConfigTableBuilder_ == null) {
        groupConfigTable_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        groupConfigTableBuilder_.clear();
      }
      uuid_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.skywalking.oap.server.configuration.service.ConfigurationServiceOuterClass.internal_static_GroupConfigurationResponse_descriptor;
    }

    @java.lang.Override
    public org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse getDefaultInstanceForType() {
      return org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse build() {
      org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse buildPartial() {
      org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse result = new org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse(this);
      int from_bitField0_ = bitField0_;
      if (groupConfigTableBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          groupConfigTable_ = java.util.Collections.unmodifiableList(groupConfigTable_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.groupConfigTable_ = groupConfigTable_;
      } else {
        result.groupConfigTable_ = groupConfigTableBuilder_.build();
      }
      result.uuid_ = uuid_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse) {
        return mergeFrom((org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse other) {
      if (other == org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse.getDefaultInstance()) return this;
      if (groupConfigTableBuilder_ == null) {
        if (!other.groupConfigTable_.isEmpty()) {
          if (groupConfigTable_.isEmpty()) {
            groupConfigTable_ = other.groupConfigTable_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGroupConfigTableIsMutable();
            groupConfigTable_.addAll(other.groupConfigTable_);
          }
          onChanged();
        }
      } else {
        if (!other.groupConfigTable_.isEmpty()) {
          if (groupConfigTableBuilder_.isEmpty()) {
            groupConfigTableBuilder_.dispose();
            groupConfigTableBuilder_ = null;
            groupConfigTable_ = other.groupConfigTable_;
            bitField0_ = (bitField0_ & ~0x00000001);
            groupConfigTableBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGroupConfigTableFieldBuilder() : null;
          } else {
            groupConfigTableBuilder_.addAllMessages(other.groupConfigTable_);
          }
        }
      }
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.apache.skywalking.oap.server.configuration.service.GroupConfigItems> groupConfigTable_ =
      java.util.Collections.emptyList();
    private void ensureGroupConfigTableIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        groupConfigTable_ = new java.util.ArrayList<org.apache.skywalking.oap.server.configuration.service.GroupConfigItems>(groupConfigTable_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.skywalking.oap.server.configuration.service.GroupConfigItems, org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.Builder, org.apache.skywalking.oap.server.configuration.service.GroupConfigItemsOrBuilder> groupConfigTableBuilder_;

    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public java.util.List<org.apache.skywalking.oap.server.configuration.service.GroupConfigItems> getGroupConfigTableList() {
      if (groupConfigTableBuilder_ == null) {
        return java.util.Collections.unmodifiableList(groupConfigTable_);
      } else {
        return groupConfigTableBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public int getGroupConfigTableCount() {
      if (groupConfigTableBuilder_ == null) {
        return groupConfigTable_.size();
      } else {
        return groupConfigTableBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public org.apache.skywalking.oap.server.configuration.service.GroupConfigItems getGroupConfigTable(int index) {
      if (groupConfigTableBuilder_ == null) {
        return groupConfigTable_.get(index);
      } else {
        return groupConfigTableBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public Builder setGroupConfigTable(
        int index, org.apache.skywalking.oap.server.configuration.service.GroupConfigItems value) {
      if (groupConfigTableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupConfigTableIsMutable();
        groupConfigTable_.set(index, value);
        onChanged();
      } else {
        groupConfigTableBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public Builder setGroupConfigTable(
        int index, org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.Builder builderForValue) {
      if (groupConfigTableBuilder_ == null) {
        ensureGroupConfigTableIsMutable();
        groupConfigTable_.set(index, builderForValue.build());
        onChanged();
      } else {
        groupConfigTableBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public Builder addGroupConfigTable(org.apache.skywalking.oap.server.configuration.service.GroupConfigItems value) {
      if (groupConfigTableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupConfigTableIsMutable();
        groupConfigTable_.add(value);
        onChanged();
      } else {
        groupConfigTableBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public Builder addGroupConfigTable(
        int index, org.apache.skywalking.oap.server.configuration.service.GroupConfigItems value) {
      if (groupConfigTableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupConfigTableIsMutable();
        groupConfigTable_.add(index, value);
        onChanged();
      } else {
        groupConfigTableBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public Builder addGroupConfigTable(
        org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.Builder builderForValue) {
      if (groupConfigTableBuilder_ == null) {
        ensureGroupConfigTableIsMutable();
        groupConfigTable_.add(builderForValue.build());
        onChanged();
      } else {
        groupConfigTableBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public Builder addGroupConfigTable(
        int index, org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.Builder builderForValue) {
      if (groupConfigTableBuilder_ == null) {
        ensureGroupConfigTableIsMutable();
        groupConfigTable_.add(index, builderForValue.build());
        onChanged();
      } else {
        groupConfigTableBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public Builder addAllGroupConfigTable(
        java.lang.Iterable<? extends org.apache.skywalking.oap.server.configuration.service.GroupConfigItems> values) {
      if (groupConfigTableBuilder_ == null) {
        ensureGroupConfigTableIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groupConfigTable_);
        onChanged();
      } else {
        groupConfigTableBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public Builder clearGroupConfigTable() {
      if (groupConfigTableBuilder_ == null) {
        groupConfigTable_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        groupConfigTableBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public Builder removeGroupConfigTable(int index) {
      if (groupConfigTableBuilder_ == null) {
        ensureGroupConfigTableIsMutable();
        groupConfigTable_.remove(index);
        onChanged();
      } else {
        groupConfigTableBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.Builder getGroupConfigTableBuilder(
        int index) {
      return getGroupConfigTableFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public org.apache.skywalking.oap.server.configuration.service.GroupConfigItemsOrBuilder getGroupConfigTableOrBuilder(
        int index) {
      if (groupConfigTableBuilder_ == null) {
        return groupConfigTable_.get(index);  } else {
        return groupConfigTableBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public java.util.List<? extends org.apache.skywalking.oap.server.configuration.service.GroupConfigItemsOrBuilder> 
         getGroupConfigTableOrBuilderList() {
      if (groupConfigTableBuilder_ != null) {
        return groupConfigTableBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(groupConfigTable_);
      }
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.Builder addGroupConfigTableBuilder() {
      return getGroupConfigTableFieldBuilder().addBuilder(
          org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.getDefaultInstance());
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.Builder addGroupConfigTableBuilder(
        int index) {
      return getGroupConfigTableFieldBuilder().addBuilder(
          index, org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.getDefaultInstance());
    }
    /**
     * <pre>
     * Include all groupConfig items.
     * All groupConfigTable.groupName should be not empty,
     * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
     * </pre>
     *
     * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
     */
    public java.util.List<org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.Builder> 
         getGroupConfigTableBuilderList() {
      return getGroupConfigTableFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.skywalking.oap.server.configuration.service.GroupConfigItems, org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.Builder, org.apache.skywalking.oap.server.configuration.service.GroupConfigItemsOrBuilder> 
        getGroupConfigTableFieldBuilder() {
      if (groupConfigTableBuilder_ == null) {
        groupConfigTableBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.apache.skywalking.oap.server.configuration.service.GroupConfigItems, org.apache.skywalking.oap.server.configuration.service.GroupConfigItems.Builder, org.apache.skywalking.oap.server.configuration.service.GroupConfigItemsOrBuilder>(
                groupConfigTable_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        groupConfigTable_ = null;
      }
      return groupConfigTableBuilder_;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <pre>
     * UUID is literal string represents the content of the config table.
     * If groupConfigTable is unchanged, then could response the same uuid, and groupConfigTable is not required.
     * </pre>
     *
     * <code>string uuid = 2;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * UUID is literal string represents the content of the config table.
     * If groupConfigTable is unchanged, then could response the same uuid, and groupConfigTable is not required.
     * </pre>
     *
     * <code>string uuid = 2;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * UUID is literal string represents the content of the config table.
     * If groupConfigTable is unchanged, then could response the same uuid, and groupConfigTable is not required.
     * </pre>
     *
     * <code>string uuid = 2;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UUID is literal string represents the content of the config table.
     * If groupConfigTable is unchanged, then could response the same uuid, and groupConfigTable is not required.
     * </pre>
     *
     * <code>string uuid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UUID is literal string represents the content of the config table.
     * If groupConfigTable is unchanged, then could response the same uuid, and groupConfigTable is not required.
     * </pre>
     *
     * <code>string uuid = 2;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uuid_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GroupConfigurationResponse)
  }

  // @@protoc_insertion_point(class_scope:GroupConfigurationResponse)
  private static final org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse();
  }

  public static org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GroupConfigurationResponse>
      PARSER = new com.google.protobuf.AbstractParser<GroupConfigurationResponse>() {
    @java.lang.Override
    public GroupConfigurationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GroupConfigurationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GroupConfigurationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GroupConfigurationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.skywalking.oap.server.configuration.service.GroupConfigurationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

