// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configuration-service.proto

package org.apache.skywalking.oap.server.configuration.service;

public interface GroupConfigurationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupConfigurationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Include all groupConfig items.
   * All groupConfigTable.groupName should be not empty,
   * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
   * </pre>
   *
   * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
   */
  java.util.List<org.apache.skywalking.oap.server.configuration.service.GroupConfigItems> 
      getGroupConfigTableList();
  /**
   * <pre>
   * Include all groupConfig items.
   * All groupConfigTable.groupName should be not empty,
   * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
   * </pre>
   *
   * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
   */
  org.apache.skywalking.oap.server.configuration.service.GroupConfigItems getGroupConfigTable(int index);
  /**
   * <pre>
   * Include all groupConfig items.
   * All groupConfigTable.groupName should be not empty,
   * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
   * </pre>
   *
   * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
   */
  int getGroupConfigTableCount();
  /**
   * <pre>
   * Include all groupConfig items.
   * All groupConfigTable.groupName should be not empty,
   * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
   * </pre>
   *
   * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
   */
  java.util.List<? extends org.apache.skywalking.oap.server.configuration.service.GroupConfigItemsOrBuilder> 
      getGroupConfigTableOrBuilderList();
  /**
   * <pre>
   * Include all groupConfig items.
   * All groupConfigTable.groupName should be not empty,
   * Each watcher implementor provides this, and it will be notified when the groupConfigTable changed.
   * </pre>
   *
   * <code>repeated .GroupConfigItems groupConfigTable = 1;</code>
   */
  org.apache.skywalking.oap.server.configuration.service.GroupConfigItemsOrBuilder getGroupConfigTableOrBuilder(
      int index);

  /**
   * <pre>
   * UUID is literal string represents the content of the config table.
   * If groupConfigTable is unchanged, then could response the same uuid, and groupConfigTable is not required.
   * </pre>
   *
   * <code>string uuid = 2;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <pre>
   * UUID is literal string represents the content of the config table.
   * If groupConfigTable is unchanged, then could response the same uuid, and groupConfigTable is not required.
   * </pre>
   *
   * <code>string uuid = 2;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();
}
