// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service-mesh-probe/service-mesh.proto

package org.apache.skywalking.apm.network.servicemesh.v3;

public interface ServiceMeshMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skywalking.v3.ServiceMeshMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Start timestamp in milliseconds of this RPC,
   * measured between the current time and midnight, January 1, 1970 UTC.
   * </pre>
   *
   * <code>int64 startTime = 1;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <pre>
   * End timestamp in milliseconds of this RPC,
   * measured between the current time and midnight, January 1, 1970 UTC.
   * </pre>
   *
   * <code>int64 endTime = 2;</code>
   * @return The endTime.
   */
  long getEndTime();

  /**
   * <code>string sourceServiceName = 3;</code>
   * @return The sourceServiceName.
   */
  java.lang.String getSourceServiceName();
  /**
   * <code>string sourceServiceName = 3;</code>
   * @return The bytes for sourceServiceName.
   */
  com.google.protobuf.ByteString
      getSourceServiceNameBytes();

  /**
   * <code>string sourceServiceInstance = 4;</code>
   * @return The sourceServiceInstance.
   */
  java.lang.String getSourceServiceInstance();
  /**
   * <code>string sourceServiceInstance = 4;</code>
   * @return The bytes for sourceServiceInstance.
   */
  com.google.protobuf.ByteString
      getSourceServiceInstanceBytes();

  /**
   * <code>string destServiceName = 5;</code>
   * @return The destServiceName.
   */
  java.lang.String getDestServiceName();
  /**
   * <code>string destServiceName = 5;</code>
   * @return The bytes for destServiceName.
   */
  com.google.protobuf.ByteString
      getDestServiceNameBytes();

  /**
   * <code>string destServiceInstance = 6;</code>
   * @return The destServiceInstance.
   */
  java.lang.String getDestServiceInstance();
  /**
   * <code>string destServiceInstance = 6;</code>
   * @return The bytes for destServiceInstance.
   */
  com.google.protobuf.ByteString
      getDestServiceInstanceBytes();

  /**
   * <code>string endpoint = 7;</code>
   * @return The endpoint.
   */
  java.lang.String getEndpoint();
  /**
   * <code>string endpoint = 7;</code>
   * @return The bytes for endpoint.
   */
  com.google.protobuf.ByteString
      getEndpointBytes();

  /**
   * <code>int32 latency = 8;</code>
   * @return The latency.
   */
  int getLatency();

  /**
   * <code>int32 responseCode = 9;</code>
   * @return The responseCode.
   */
  int getResponseCode();

  /**
   * <pre>
   * Status represents the response status of this calling.
   * </pre>
   *
   * <code>bool status = 10;</code>
   * @return The status.
   */
  boolean getStatus();

  /**
   * <code>.skywalking.v3.Protocol protocol = 11;</code>
   * @return The enum numeric value on the wire for protocol.
   */
  int getProtocolValue();
  /**
   * <code>.skywalking.v3.Protocol protocol = 11;</code>
   * @return The protocol.
   */
  org.apache.skywalking.apm.network.servicemesh.v3.Protocol getProtocol();

  /**
   * <code>.skywalking.v3.DetectPoint detectPoint = 12;</code>
   * @return The enum numeric value on the wire for detectPoint.
   */
  int getDetectPointValue();
  /**
   * <code>.skywalking.v3.DetectPoint detectPoint = 12;</code>
   * @return The detectPoint.
   */
  org.apache.skywalking.apm.network.common.v3.DetectPoint getDetectPoint();

  /**
   * <pre>
   * NONE, mTLS, or TLS
   * </pre>
   *
   * <code>string tlsMode = 13;</code>
   * @return The tlsMode.
   */
  java.lang.String getTlsMode();
  /**
   * <pre>
   * NONE, mTLS, or TLS
   * </pre>
   *
   * <code>string tlsMode = 13;</code>
   * @return The bytes for tlsMode.
   */
  com.google.protobuf.ByteString
      getTlsModeBytes();

  /**
   * <pre>
   * The sidecar/proxy internal error code, the value bases on the implementation.
   * The envoy internal error codes are listed here, https://www.envoyproxy.io/docs/envoy/latest/api-v2/data/accesslog/v2/accesslog.proto#data-accesslog-v2-responseflags
   * </pre>
   *
   * <code>string internalErrorCode = 14;</code>
   * @return The internalErrorCode.
   */
  java.lang.String getInternalErrorCode();
  /**
   * <pre>
   * The sidecar/proxy internal error code, the value bases on the implementation.
   * The envoy internal error codes are listed here, https://www.envoyproxy.io/docs/envoy/latest/api-v2/data/accesslog/v2/accesslog.proto#data-accesslog-v2-responseflags
   * </pre>
   *
   * <code>string internalErrorCode = 14;</code>
   * @return The bytes for internalErrorCode.
   */
  com.google.protobuf.ByteString
      getInternalErrorCodeBytes();

  /**
   * <pre>
   * The tcp detail of the mesh metrics if it's a TCP metrics, otherwise should be empty.
   * </pre>
   *
   * <code>.skywalking.v3.TCPInfo tcp = 15;</code>
   * @return Whether the tcp field is set.
   */
  boolean hasTcp();
  /**
   * <pre>
   * The tcp detail of the mesh metrics if it's a TCP metrics, otherwise should be empty.
   * </pre>
   *
   * <code>.skywalking.v3.TCPInfo tcp = 15;</code>
   * @return The tcp.
   */
  org.apache.skywalking.apm.network.servicemesh.v3.TCPInfo getTcp();
  /**
   * <pre>
   * The tcp detail of the mesh metrics if it's a TCP metrics, otherwise should be empty.
   * </pre>
   *
   * <code>.skywalking.v3.TCPInfo tcp = 15;</code>
   */
  org.apache.skywalking.apm.network.servicemesh.v3.TCPInfoOrBuilder getTcpOrBuilder();

  /**
   * <pre>
   * Internal request(response) latency is the time cost inside the Envoy sidecar proxy.
   * For more details, check https://www.envoyproxy.io/docs/envoy/v1.22.0/api-v3/data/accesslog/v3/accesslog.proto.html#data-accesslog-v3-accesslogcommon.
   * internalRequestLatencyNanos is the interval between the first downstream byte received and the first upstream byte sent
   * </pre>
   *
   * <code>int64 internalRequestLatencyNanos = 16;</code>
   * @return The internalRequestLatencyNanos.
   */
  long getInternalRequestLatencyNanos();

  /**
   * <pre>
   * internalResponseLatencyNanos = time_to_first_downstream_tx_byte - time_to_first_upstream_rx_byte;
   * | ... request workflow  ... | upstream | ----- response -----&gt; |                proxy                | ------- response -------&gt; | client  |
   * |                 time_to_first_upstream_rx_byte               |
   * |                                  time_to_last_downstream_tx_byte                                                               |
   *                                                                |              internalResponseLatencyNanos                       |
   * </pre>
   *
   * <code>int64 internalResponseLatencyNanos = 17;</code>
   * @return The internalResponseLatencyNanos.
   */
  long getInternalResponseLatencyNanos();

  /**
   * <code>repeated .skywalking.v3.KeyStringValuePair sourceInstanceProperties = 18;</code>
   */
  java.util.List<org.apache.skywalking.apm.network.common.v3.KeyStringValuePair> 
      getSourceInstancePropertiesList();
  /**
   * <code>repeated .skywalking.v3.KeyStringValuePair sourceInstanceProperties = 18;</code>
   */
  org.apache.skywalking.apm.network.common.v3.KeyStringValuePair getSourceInstanceProperties(int index);
  /**
   * <code>repeated .skywalking.v3.KeyStringValuePair sourceInstanceProperties = 18;</code>
   */
  int getSourceInstancePropertiesCount();
  /**
   * <code>repeated .skywalking.v3.KeyStringValuePair sourceInstanceProperties = 18;</code>
   */
  java.util.List<? extends org.apache.skywalking.apm.network.common.v3.KeyStringValuePairOrBuilder> 
      getSourceInstancePropertiesOrBuilderList();
  /**
   * <code>repeated .skywalking.v3.KeyStringValuePair sourceInstanceProperties = 18;</code>
   */
  org.apache.skywalking.apm.network.common.v3.KeyStringValuePairOrBuilder getSourceInstancePropertiesOrBuilder(
      int index);

  /**
   * <code>repeated .skywalking.v3.KeyStringValuePair destInstanceProperties = 19;</code>
   */
  java.util.List<org.apache.skywalking.apm.network.common.v3.KeyStringValuePair> 
      getDestInstancePropertiesList();
  /**
   * <code>repeated .skywalking.v3.KeyStringValuePair destInstanceProperties = 19;</code>
   */
  org.apache.skywalking.apm.network.common.v3.KeyStringValuePair getDestInstanceProperties(int index);
  /**
   * <code>repeated .skywalking.v3.KeyStringValuePair destInstanceProperties = 19;</code>
   */
  int getDestInstancePropertiesCount();
  /**
   * <code>repeated .skywalking.v3.KeyStringValuePair destInstanceProperties = 19;</code>
   */
  java.util.List<? extends org.apache.skywalking.apm.network.common.v3.KeyStringValuePairOrBuilder> 
      getDestInstancePropertiesOrBuilderList();
  /**
   * <code>repeated .skywalking.v3.KeyStringValuePair destInstanceProperties = 19;</code>
   */
  org.apache.skywalking.apm.network.common.v3.KeyStringValuePairOrBuilder getDestInstancePropertiesOrBuilder(
      int index);
}
